package cmx.acuntia.es.museocmx;


import java.util.ArrayList;
import java.util.List;


public class Datasource {

    static List GOYA = new ArrayList<>();
    static List VELAZQUEZ = new ArrayList<>();
    static List PICASSO = new ArrayList<>();
    static List VAN_GOGH = new ArrayList<>();
    static List MODERNO = new ArrayList<>();

    static{

        GOYA.add(new Cuadro("Los fusilamientos del 3 de Mayo","Goya",R.mipmap.fusilamientos,"Los Fusilamientos del 3 de Mayo en la Montaña del Príncipe Pío de Madrid, es uno de los mayores logros de la pintura española y posiblemente un hito de la pintura universal. Es uno de los cuadros de temática histórica más dramáticos de la historia del arte. Goya plasma en el lienzo toda la fuerza y el dramatismo del hecho histórico, con un lenguaje plástico, no visto hasta ese momento y que se anticipa al expresionismo moderno. Los rostros de los fusilados expresan el horror del momento en contraposición de los soldados que aparecen como autómatas sin rostro.",R.drawable.fusilamientos));
        GOYA.add(new Cuadro("El 2 de mayo","Goya",R.mipmap.dosdemayo,"El lienzo \"El Dos de Mayo\", conocido también como \"La carga de los mamelucos en la Puerta del Sol de Madrid\", junto con \"Los Fusilamientos del 3 de Mayo\", fueron encargados a Goya después de la guerra de la Independencia en 1814, por la Junta de Regencia, para perpetuar las acciones heroicas del pueblo de Madrid contra las tropas napoleónicas. Estas dos obras son consideradas de forma unánime las mejores de toda su producción. ",R.drawable.dosdemayo));
        GOYA.add(new Cuadro("La familia de Carlos IV","Goya",R.mipmap.carlosiv," \"La Familia de Carlos IV\", oleo sobre lienzo, pintado por Goya en 1800. Es un retrato colectivo de la familia real, que se conserva en el Museo del Prado. El cuadro, es la culminación de Goya, después de una amplia labor como retratista. Es una de sus composiciones más complejas. ",R.drawable.familiacarlosiv));
        GOYA.add(new Cuadro("La maja desnuda","Goya",R.mipmap.desnuda,"\"La Maja Desnuda\", es una de las más celebres obras de Goya. Pintada antes de 1800, luego formaría pareja con \"La Maja Vestida\". Se especula que el retrato represente a la Duquesa de Alba. Es una obra audaz y atrevida para su época, como lo es la expresión del rostro y la actitud corporal de la modelo, que parece sonreír satisfecha de sus gracias. ",R.drawable.majadesnuda));
        GOYA.add(new Cuadro("La maja vestida","Goya",R.mipmap.vestida," Es una de las obras más conocidas de Goya, realizado en oleo sobre lienzo de 95 por 188 cm. Fue pintado entre 1802 y 1808 y se encuentra en el Museo del Prado. Es hermano de \"La Maja Desnuda\". ",R.drawable.majavestida));
        GOYA.add(new Cuadro("Saturno devorande a un hijo","Goya",R.mipmap.saturno," Es una de las pinturas al oleo sobre revoco, que formó parte de la decoración de los muros de la casa que Goya adquirió en 1819, llamada la Quinta del Sordo. La obra pertenece a la serie de Pinturas Negras. ",R.drawable.saturno));

        VELAZQUEZ.add(new Cuadro("La redención de Breda", "Velázquez", R.mipmap.redencionbreda, "El cuadro hace referencia a la rendición de Breda, dentro de la guerra de los Países Bajos. Está tratado con un gran realismo en los rostros, tratados como retratos y las referencias que en el mismo hace al momento histórico, como la entrega de las llaves de la plaza, el número de lanzas españolas vencedoras de la contienda, a la caballerosidad española con los vencidos, así como el tratamiento de los ropajes de los personajes. Una obra maestra y universal.",R.drawable.redencionbreda));
        VELAZQUEZ.add(new Cuadro("Retrato de Inocencio X", "Velázquez", R.mipmap.inocencio, "Óleo sobre lienzo, realizado por Velázquez en el verano de 1650, actualmente se encuentra en la Galería Doria Panphili de Roma. El cuadro fue pintado en Roma y el Pontífice posó para el pintor. La firma del cuadro aparece en el papel que sostiene el Papa. ",R.drawable.inocencio));
        VELAZQUEZ.add(new Cuadro("Las Meninas", "Velázquez", R.mipmap.meninas, "También conocido como la Familia de Felipe IV, es un óleo sobre lienzo de grandes dimensiones, son tres bandas de tela, cosidas verticalmente. Es considerada la obra maestra de Velázquez y corresponde a la última época del pintor. ",R.drawable.meninas));
        VELAZQUEZ.add(new Cuadro("La fabula de Aracne", "Velázquez", R.mipmap.fabula, "También conocida como “Las hilanderas”. Es un óleo sobre lienzo de gran tamaño, conservado en el Museo del Prado. Esta pintura, está considerada como uno de los máximos exponentes del Barroco español y una de las obras maestras de Velázquez. ",R.drawable.fabula));
        VELAZQUEZ.add(new Cuadro("El bufón don Sebastián de Morra", "Velázquez", R.mipmap.bufonmorra, "Es un óleo sobre lienzo, pintado por Velázquez hacia 1645 y que se conserva en el Museo del Prado. Pertenece a una serie de retratos de bufones de la corte, pintados por Velázquez, para decorar estancias secundarias de los palacios reales, en los que dado su carácter informal, el artista pudo ensayar nuevos recursos expresivos con mayor libertad que en los retratos oficiales de la familia real, dada su carga representativa",R.drawable.bufonmorra));
        VELAZQUEZ.add(new Cuadro("El aguador de Sevilla", "Velázquez", R.mipmap.aguador, "Es un bodegón, óleo sobre lienzo, de estilo barroco, realizado por Velázquez en los últimos años de su estancia en Sevilla. Se conserva actualmente en el Museo Wellington, siendo regalada por Fernando VII al general Arthur Wellesley, en reconocimiento a su ayuda en la Guerra de la Independencia. ",R.drawable.aguador));

        PICASSO.add(new Cuadro("El Guernica","Picasso", R.mipmap.guernica, "El Guernica, es el más famoso cuadro de Pablo Picasso, pintado entre los meses de mayo y junio de 1937 y el título alude al bombardeo de Guernica del 26 de abril de ese mismo año, durante la Guerra Civil Española." ,R.drawable.guernica));
        PICASSO.add(new Cuadro("Las señoritas de Avignon","Picasso", R.mipmap.avignon, "Las Señoritas de la Calle de Avinyó, fue pintado por Pablo Picasso en 1907, óleo sobre lienzo de grandes dimensiones, se encuentra en el Museo de Arte Moderno de New York. Este cuadro marcó el inicio de su periodo Africano o Protocubismo, punto de partida donde el artista rompe con el realismo. Obra muy criticada e incomprendida por el mundo artístico de la época. " ,R.drawable.avignon));
        PICASSO.add(new Cuadro("Muchacho con pipa","Picasso", R.mipmap.muchacho, "Garcon a la Pipe, fue pintado por Picasso en 1905, cuando tenía 24 años, durante su Periodo Rosa. Óleo sobre lienzo, representa a un niño parisino con una pipa en la mano izquierda y con una guirnalda o corona de flores. " ,R.drawable.muchacho));
        PICASSO.add(new Cuadro("Dora Maar au chat","Picasso", R.mipmap.dora, "Dora Maar con gato, óleo sobre lienzo, es un cuadro pintado por Picasso en 1941, representa a Dora Maar, amante croata del pintor, sentada en un sillón con un gato posado sobre uno de sus hombros. Dora Maar, tenía 29 años y Picasso 55 cuando se conocieron, ella era una artista también, colaboró con él en la ejecución del Guernica, y su influencia dio lugar a algunos de los retratos más poderosos y atrevidos de su carrera. " ,R.drawable.dora));
        PICASSO.add(new Cuadro("La vida","Picasso", R.mipmap.vida, "Pintado por Picasso en 1903, es uno de los mayores y más complejos cuadros pintados por Picasso en la época azul, considerado su trabajo más importante de estos años. Obra de un simbolismo inusual y sujeto a múltiples interpretaciones académicas, sobre las que el artista nunca se pronunció. Picasso, realizó cuatro bocetos preparatorios para el cuadro, variando la composición de las figuras dos veces, cabe destacar que la figura masculina, que empezó siendo un autorretrato, acabó siendo un retrato de su amigo Carlos Casagemas. La Vida, resume la mayor parte de los temas y la atmósfera de la” época azul”. " ,R.drawable.vida));
        PICASSO.add(new Cuadro("La maternidad","Picasso", R.mipmap.maternidad, "Es una de las obras más importantes pintadas por Picasso en su época azul. Pintado en 1901, representa a una madre besando a su hijo tiernamente en la frente, hay que destacar la fuerza emocional de la escena, pese a la frialdad de los tonos azules. " , R.drawable.maternidad));

        VAN_GOGH.add(new Cuadro("Los comedores de patatas", "Van Gogh", R.mipmap.comedores, "Oleo sobre lienzo, pintado por Van Gogh en 1885, de estilo realista, en tonos oscuros y trazos duros y acusados, obra maestra del periodo holandés. Realizó pruebas y bocetos previos, algunos de los cuales no llegó ni a firmar, para evitar confusiones en el mercado del arte. ",R.drawable.comedores ));
        VAN_GOGH.add(new Cuadro("La cosecha", "Van Gogh", R.mipmap.cosecha, "Oleo sobre lienzo, conocido también como La Llanura de Crau, cerca de Arles, con Mont Mayour al fondo; fue pintado por Van Gogh en 1888, mide 72 de alto por 92 de ancho y se encuentra en el Museo Van Gogh de Amsterdam. ",R.drawable.cosecha ));
        VAN_GOGH.add(new Cuadro("El puente de Langlois", "Van Gogh", R.mipmap.langlois, "Oleo sobre lienzo, de estilo Neo-impresionista, pintado por Van Gogh en 1888. En la zona de Arlés, descubrió una serie de puentes de madera de estilo holandés sobre el Ródano, realizando un buen número de cuadros sobre ellos ya que le recordaban a su tierra natal. En el más conocido, el puente lo sitúa al fondo de la composición, colocando en primer plano un grupo de mujeres lavando. ",R.drawable.langlois ));
        VAN_GOGH.add(new Cuadro("La habitación de Arles", "Van Gogh", R.mipmap.habitacion, "Oleo sobre lienzo, de estilo postimpresionista, que representa el dormitorio de Van Gogh durante su estancia en Arlés. Sobre el mismo motivo pintó tres cuadros, casi idénticos. Con las tonalidades que emplea quiere expresar la tranquilidad, también hace referencia a Japón en la sencillez de la habitación, una cama y dos sellas. ",R.drawable.habitacion ));
        VAN_GOGH.add(new Cuadro("La noche estrellada", "Van Gogh", R.mipmap.noche, "Pintado por Van Gogh en 1889, obra maestra de estilo postimpresionista, se encuentra el Museo de Arte Moderno de New York. El cuadro muestra una vista nocturna desde la ventana del sanatorio de Saint-Rémy-de-Provence, donde se recluyó hacia el final de su vida. ",R.drawable.noche ));
        VAN_GOGH.add(new Cuadro("Los girasoles", "Van Gogh", R.mipmap.girasoles, "Van Gogh, pintó en 1888-89 una serie de cuadros con el tema de girasoles. De la serie, hay tres cuadros similares con catorce girasoles en un jarrón, dos con doce girasoles, uno con tres y otro con cinco. Pintó los cuatro primeros en Agosto de 1888, cuando vivía en Arlés y los otros tres similares al año siguiente. \n",R.drawable.girasoles ));
        VAN_GOGH.add(new Cuadro("Autorretrato", "Van Gogh", R.mipmap.autoretrato, "Uno de los más bellos y significativos, es el realizado en Septiembre de 1889, después de su recuperación, en él las líneas onduladas se adueñan de la composición, el azul y el naranja, colores complementarios hacen un interesante contraste, así mismo las líneas marcadas de la chaqueta y ojos, con una soltura y rapidez por encima de las formulas estilísticas, lo que utiliza para expresar su personalidad, como ya hicieran otros grandes maestros de la pintura. Este cuadro se encuentra en el Museo De Orsay, en Paris, el resto en diferentes museos.",R.drawable.autoretrato ));

        MODERNO.add(new Cuadro("La Gioconda","Leonardo Da Vinci", R.mipmap.gioconda, "Es una pintura del pintor italiano Leonardo da Vinci, realizada al óleo sobre tabla entre 1503 – 1505, y conservada en el museo del Louvre de París. Es una de las más destacadas obras del Cinquecento italiano, en lo que se ponen de manifiesto las características de este estilo, que se consiguen en la Italia del siglo XVI a partir de los ensayos de los pintores del Quattrocento. ", R.drawable.gioconda));
        MODERNO.add(new Cuadro("El Grito", "Edvard Munch", R.mipmap.grito, "Usando óleo y pastel sobre cartón, Edvard Munch pintó su obra más famosa, El Grito, hacia 1893. Ofrece una figura fantasmal que se parece al anfitrión de Historias de la Cripta, el fondo de esta pintura expresionista se dice que es Oslo, Noruega.", R.drawable.grito));
        MODERNO.add(new Cuadro("La persistencia de la memoria", "Salvador Dalí", R.mipmap.persistencia, "Pintada en 1931 por otro artista español, La persistencia de la Memoria de Salvador Dalí es una de las piezas mas reconocibles e individuales de la historia del arte. Representa una costa lúgubre cubierta de relojes derretidos, se cree que la teoría de Einstein de la relatividad inspiró esta extraña obra.", R.drawable.persistencia));
        MODERNO.add(new Cuadro("La joven de la perla", "Johannes Vermeer", R.mipmap.perla, "Esta obra no pertenece al género del  retrato, sino a un género de pintura propio del barroco flamenco holandés conocido como la  tronie (“rostro” en holandés), que se caracterizaba por representar retratos, normalmente de pequeño tamaño, en las que el protagonista muestra una expresión facial exagerada. Aunque el tronie típico mostraba un retrato de una persona de medio cuerpo, o del busto únicamente, no solían realizarse con intención retratística, sino más bien para mostrar las dotes artísticas del pintor, y su maestría a la hora de captar gestos, unas veces grotescos y otras de expresiones inusuales Rembrandt – La joven. Por ello, raro es el caso de tronies en los que se conoce el nombre del retratado.", R.drawable.perla));
//        MODERNO.add(new Cuadro("", "", R.mipmap., "", R.drawable.));
//        MODERNO.add(new Cuadro("", "", R.mipmap., "", R.drawable.));
//        MODERNO.add(new Cuadro("", "", R.mipmap., "", R.drawable.));
//        MODERNO.add(new Cuadro("", "", R.mipmap., "", R.drawable.));


    }

}

